services:
  notifications-api:
    build: ./backend/notifications-api
    container_name: notifications-api
    volumes:
      - ./backend/notifications-api:/var/www/html
    expose:
      - "9000"

  notifications-nginx:
    image: nginx:alpine
    container_name: notifications-nginx
    volumes:
      - ./backend/notifications-api:/var/www/html
      - ./infra/nginx/notifications.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - notifications-api
